@isTest
public class FakeStoreCalloutMock implements HttpCalloutMock {
    public HTTPResponse respond(HTTPRequest req) {
        HttpResponse res = new HttpResponse();
        res.setHeader('Content-Type', 'application/json');
        
        res.setBody('[{"id":1,"title":"Super Fast Car","price":109.95,"description":"Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday"}]');
        res.setStatusCode(200);
        
        //System.debug(res.getBody());
        return res;
    }
}